title: Tianze Quan's Homepage
page-top-title: Tianze Quan
top-section-bg-text: Operation Research and Information Engineering
home-subtitle: Tianze Quan&ensp;
copyright-text: '&copy; Tianze Quan 2025-2026. All Rights Reserved.'
